FROM python
WORKDIR c:\Users\alina\School\3.1\Programowanie_Współbieżne_i_Rozproszone\PWiR\HelloDocker
COPY hello.py c:\Users\alina\School\3.1\Programowanie_Współbieżne_i_Rozproszone\PWiR\HelloDocker
CMD ["python", "hello.py"]